### ISSUE TITLE
Broken edit links for non-latest branches

### ISSUE THREAD

**Issue by bdarnell** [snide/sphinx_rtd_theme#236] opened 2015-09-03 02:32 UTC
On a page like http://www.tornadoweb.org/en/stable/, the "edit on github" link in the upper right is broken because it points to https://github.com/tornadoweb/tornado/blob/origin/stable/docs/index.rst (the 'origin' directory needs to be removed from the path). On the lower left, clicking "v: stable" for the menu and then "Edit" works (linking to https://github.com/tornadoweb/tornado/edit/stable/docs/index.rst). 

The "latest" branch works fine (linking to "master"); this is only a problem for pages based on other branches

**Comment by agjohnson** [comment] 2015-09-09 05:28
This is a duplicate of #237, which should be addressed in RTD it seems.

**Closed by agjohnson** 2015-09-09 05:28 UTC
